### ISSUE TITLE
A better name for the CLI

### ISSUE THREAD

**Issue by taktran** [Financial-Times/github-repositories-contents-search#11]
Currently `grcs` (Github Repositories Content Search)

Ideas?

**Comment by taktran** [comment]
Simple one:

`gs` => Github Search
`ebi` => 🦐  Prawn/Shrimp in Japanese (along the lines of Tako 🐙) - trawling through the repos?

**Comment by adambraimbridge** [comment]
`rummage`

**Comment by taktran** [comment]
Going with Ebi (🦐 ) - short, sweet and crawls around in the sea of code
