### ISSUE TITLE
Print non-matched repos to stderr

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/github-repositories-contents-search#31]
If I'm looking for all repos with a `web` process in their `Procfile`. Some information that would be helpful to know about is repositories that do have a `Procfile` but don't match for `web`.

Ideal would be...

```
$ cat repos.txt | ./bin/gcrs.js contents Procfile web
Financial-Times/next-front-page
404 ERROR: file 'Procfile' not found in 'Financial-Times/x-dash'
ERROR: file 'Procfile' has no match for 'web' in 'Financial-Times/tako'
```

First line on stdout, and the second and third on stderr.

**Comment by taktran** [comment]
👍 Agree. Although, I think it should be `INFO:` instead of `ERROR:`, as it's not really an error.

Also, means you can filter it out apart from the `ERROR`s

**Comment by taktran** [comment]
Also, agree that logging to `stderr` makes sense, so that it doesn't pollute `stdout`

**Comment by taktran** [comment]
For reference, this could be better improved with more reporting formats: https://github.com/Financial-Times/github-repositories-contents-search/issues/26
